### ISSUE TITLE
@actual-api is not the latest, causing conflict with latest actual-server

### ISSUE THREAD

**Issue by virtualJonesie** [sakowicz/actual-ai#26]
I am running the latest actual-server. version 24.8.0. The current API version is 6.9.0, per https://www.npmjs.com/package/@actual-app/api

When running the actual-ai Docker container, I receive the following error. According to the actual Discord, this appears to be a mismatch between the API version used by actual-ai and actual-server. 
```
actual-ai-1  | Application started
actual-ai-1  | Starting classification process
actual-ai-1  | (node:1) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
actual-ai-1  | (Use `node --trace-warnings ...` to show where the warning was created)
actual-ai-1  | Database is out of sync with migrations: {
actual-ai-1  |   appliedIds: [
actual-ai-1  |     1548957970627, 1550601598648, 1555786194328,
actual-ai-1  |     1561751833510, 1567699552727, 1582384163573,
actual-ai-1  |     1597756566448, 1608652596043, 1608652596044,
actual-ai-1  |     1612625548236, 1614782639336, 1615745967948,
actual-ai-1  |     1616167010796, 1618975177358, 1632571489012,
actual-ai-1  |     1679728867040, 1681115033845, 1682974838138,
actual-ai-1  |     1685007876842, 1686139660866, 1688749527273,
actual-ai-1  |     1688841238000, 1691233396000, 1694438752000,
actual-ai-1  |     1697046240000, 1704572023730, 1704572023731,
actual-ai-1  |     1707267033000, 1712784523000, 1716359441000,
actual-ai-1  |     1720310586000, 1720664867241, 1720665000000
actual-ai-1  |   ],
actual-ai-1  |   available: [
actual-ai-1  |     '1548957970627_remove-db-version.sql',
actual-ai-1  |     '1550601598648_payees.sql',
actual-ai-1  |     '1555786194328_remove_category_group_unique.sql',
actual-ai-1  |     '1561751833510_indexes.sql',
actual-ai-1  |     '1567699552727_budget.sql',
actual-ai-1  |     '1582384163573_cleared.sql',
actual-ai-1  |     '1597756566448_rules.sql',
actual-ai-1  |     '1608652596043_parent_field.sql',
actual-ai-1  |     '1608652596044_trans_views.sql',
actual-ai-1  |     '1612625548236_optimize.sql',
actual-ai-1  |     '1614782639336_trans_views2.sql',
actual-ai-1  |     '1615745967948_meta.sql',
actual-ai-1  |     '1616167010796_accounts_order.sql',
actual-ai-1  |     '1618975177358_schedules.sql',
actual-ai-1  |     '1632571489012_remove_cache.js',
actual-ai-1  |     '1679728867040_rules_conditions.sql',
actual-ai-1  |     '1681115033845_add_schedule_name.sql',
actual-ai-1  |     '1682974838138_remove_payee_rules.sql',
actual-ai-1  |     '1685007876842_add_category_hidden.sql',
actual-ai-1  |     '1686139660866_remove_account_type.sql',
actual-ai-1  |     '1688749527273_transaction_filters.sql',
actual-ai-1  |     '1688841238000_add_account_type.sql',
actual-ai-1  |     '1691233396000_add_schedule_next_date_tombstone.sql',
actual-ai-1  |     '1694438752000_add_goal_targets.sql',
actual-ai-1  |     '1697046240000_add_reconciled.sql',
actual-ai-1  |     '1704572023730_add_account_sync_source.sql',
actual-ai-1  |     '1704572023731_add_missing_goCardless_sync_source.sql',
actual-ai-1  |     '1707267033000_reports.sql',
actual-ai-1  |     '1712784523000_unhide_input_group.sql'
actual-ai-1  |   ]
actual-ai-1  | }
actual-ai-1  | Error updating Error: out-of-sync-migrations
actual-ai-1  |     at checkDatabaseValidity (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:39329:31)
actual-ai-1  |     at Module.migrate (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:39337:17)
actual-ai-1  |     at async runMigrations (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:43144:17)
actual-ai-1  |     at async updateVersion (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:43163:17)
actual-ai-1  |     at async loadBudget (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:38945:21)
actual-ai-1  |     at async handlers.load-budget (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:38775:29)
actual-ai-1  |     at async handlers.download-budget (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:38745:17)
actual-ai-1  |     at async handlers.api/download-budget (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:29478:32)
actual-ai-1  | TypeError: Cannot read properties of undefined (reading 'timestamp')
actual-ai-1  |     at _fullSync (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:42483:98)
actual-ai-1  |     at /opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:42395:38
actual-ai-1  |     at /opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:43341:38
actual-ai-1  |     at initialFullSync (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:42381:38)
actual-ai-1  |     at handlers.sync-budget (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:38760:94)
actual-ai-1  |     at handlers.download-budget (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:38748:55)
actual-ai-1  |     at async handlers.api/download-budget (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:29478:32)
actual-ai-1  | [Exception] TypeError: Cannot read properties of undefined (reading 'timestamp')
actual-ai-1  |     at _fullSync (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:42483:98)
actual-ai-1  |     at /opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:42395:38
actual-ai-1  |     at /opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:43341:38
actual-ai-1  |     at initialFullSync (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:42381:38)
actual-ai-1  |     at handlers.sync-budget (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:38760:94)
actual-ai-1  |     at handlers.download-budget (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:38748:55)
actual-ai-1  |     at async handlers.api/download-budget (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:29478:32)
actual-ai-1  | Full error details {
actual-ai-1  |   message: "Cannot read properties of undefined (reading 'timestamp')",
actual-ai-1  |   reason: undefined,
actual-ai-1  |   meta: undefined
actual-ai-1  | }
actual-ai-1  | An error occurred: Error: Something went wrong trying to download that file, sorry! Visit https://actualbudget.org/contact/ for support. (reason: undefined)
actual-ai-1  |     at handlers.api/download-budget (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:29483:27)
actual-ai-1  | node:internal/process/promises:288
actual-ai-1  |             triggerUncaughtException(err, true /* fromPromise */);
actual-ai-1  |             ^
actual-ai-1  |
actual-ai-1  | Error: Something went wrong trying to download that file, sorry! Visit https://actualbudget.org/contact/ for support. (reason: undefined)
actual-ai-1  |     at handlers.api/download-budget (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:29483:27)
actual-ai-1  |
actual-ai-1  | Node.js v18.20.3
actual-ai-1 exited with code 1
```

Would it be possible to update to the latest version of the API, or at least provide guidance on how I could update my package.json or package-lock.json file to allow for the latest API version?

Thanks!

**Comment by sakowicz** [comment]
#21 
Please update the app

**Comment by virtualJonesie** [comment]
That worked. Thank you for the prompt response and the great work!
